name: BUILD_DOCKER_APP

on:
  push:
    tags:
       - '*'

# env:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPO
        uses: actions/checkout@v2
        
      - name: DOCKER LOGIN
        run: ls -l
        # run: echo "${GITHUB_REF#refs/*/}"