name: BUILD_DOCKER_APP

on:
  push:
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPO
        uses: actions/checkout@v2
        
      - name: DOCKER LOGIN
        run: cat GCP_SERVICE_ACC_KEY | docker login -u _json_key --password-stdin https://us-east1-docker.pkg.dev
        # run: echo "${GITHUB_REF#refs/*/}"