name: BUILD_DOCKER_APP

on:
  push:
    tags:
       - '*'

env:
  DOCKER_IMAGE_TAG: ${GITHUB_REF#refs/*/}
  DOCKER_REGISTRY: us-east1-docker.pkg.dev
  GCP_PROJECT_ID: ppetrov-internal-402521
  GCP_DOCKER_REPO: ex-zh-part1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPO
        uses: actions/checkout@v2
        
      - name: GCP DOCKER REGISTRY LOGIN
        run: echo ${{ secrets.GCP_SERVICE_ACC_KEY_ENCODED }} | docker login -u _json_key_base64 --password-stdin ${{ env.DOCKER_REGISTRY }}

      - name: BUILD DOCKER IMAGE
        run: cd app/ && docker build -f ./Dockerfile -t ${{ env.DOCKER_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_DOCKER_REPO }}/${{ env.DOCKER_IMAGE_TAG }} .

      - name: PUSH DOCKER IMAGE
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_DOCKER_REPO }}/${{ env.DOCKER_IMAGE_TAG }}